# Main Navigation
main:
  # Get Started
  - name: "Get Started"
    weight: 1
    hasChildren: true
  - name: "About NWB"
    weight: 1
    url: "about-nwb/"
    parent: "Get Started"
  - name: "Converting Data to NWB"
    weight: 2
    url: "convert/"
    parent: "Get Started"
  - name: "Documentation"
    weight: 3
    url: "https://nwb-overview.readthedocs.io"
    parent: "Get Started"
  
  # The Standard
  - name: "The Standard"
    weight: 2
    hasChildren: true
  - name: "Specification"
    weight: 1
    url: "https://nwb-schema.readthedocs.io/en/latest/format.html"
    parent: "The Standard"
  - name: "Policies"
    weight: 2
    url: "policies/"
    parent: "The Standard"
  - name: "Enhancement Proposals"
    weight: 3
    url: "enhancement-proposals/"
    parent: "The Standard"
  - name: "Extensions (NDX Catalog)"
    weight: 4
    url: "https://nwb-extensions.github.io"
    parent: "The Standard"
  
  # Tools & Archives
  - name: "Tools & Archives"
    weight: 3
    hasChildren: true
  - name: "NWB Software Ecosystem"
    weight: 1
    url: "nwb-software/"
    parent: "Tools & Archives"
  - name: "Core Tools"
    weight: 2
    url: "tools/core/"
    parent: "Tools & Archives"
  - name: "Community Tools"
    weight: 3
    url: "tools/community/"
    parent: "Tools & Archives"
  - name: "Data Archives"
    weight: 4
    url: "archives/"
    parent: "Tools & Archives"
  
  # Community
  - name: "Community"
    weight: 4
    hasChildren: true
  - name: "News & Updates"
    weight: 1
    url: "news/"
    parent: "Community"
  - name: "Events"
    weight: 2
    url: "events/"
    parent: "Community"
  - name: "Community Gallery"
    weight: 3
    url: "community/gallery/"
    parent: "Community"
  - name: "Organizing NWB Events"
    weight: 4
    url: "organizing-nwb-events/"
    parent: "Community"
  - name: "Teaching with NWB"
    weight: 5
    url: "community/educators/"
    parent: "Community"
  - name: "Extending NWB"
    weight: 6
    url: "extending-nwb/"
    parent: "Community"
  - name: "Working Groups"
    weight: 7
    url: "working-groups/"
    parent: "Community"
  - name: "Supporting NWB"
    weight: 8
    url: "supporting-nwb/"
    parent: "Community"
  - name: "Team"
    weight: 9
    url: "team/"
    parent: "Community"
  
  # Resources
  - name: "Resources"
    weight: 5
    hasChildren: true
  - name: "Publications"
    weight: 1
    url: "publications/"
    parent: "Resources"
  - name: "Online Resources"
    weight: 2
    url: "online-resources/"
    parent: "Resources"
  - name: "Grants & Projects"
    weight: 3
    url: "grants-and-projects/"
    parent: "Resources"
  - name: "Training & Event Materials"
    weight: 4
    url: "training-materials/"
    parent: "Resources"
  - name: "FAQ"
    weight: 5
    url: "faq/"
    parent: "Resources"
  
  # Contact
  - name: "Contact"
    weight: 6
    url: "contact-us/"

# Footer
# Footer Menus
quick_links:
  - name: "Get Started"
    weight: 1
    url: "/about-nwb"
  - name: "Documentation"
    weight: 2
    url: "https://nwb-overview.readthedocs.io"
  - name: "Software"
    weight: 3
    url: "/nwb-software"
  - name: "Team"
    weight: 4
    url: "/team"

community_links:
  - name: "News & Updates"
    weight: 1
    url: "/news"
  - name: "Events"
    weight: 2
    url: "/events"
  - name: "Community Gallery"
    weight: 3
    url: "/community/gallery"
  - name: "Organizing NWB Events"
    weight: 4
    url: "/organizing-nwb-events"
  - name: "Teaching with NWB"
    weight: 5
    url: "/community/educators"
  - name: "Extending NWB"
    weight: 6
    url: "/extending-nwb"
  - name: "Working Groups"
    weight: 7
    url: "/working-groups"
  - name: "Supporting NWB"
    weight: 8
    url: "/supporting-nwb"
  - name: "Contact Us"
    weight: 9
    url: "/contact-us"

resources:
  - name: "Publications"
    weight: 1
    url: "/publications"
  - name: "Online Resources"
    weight: 2
    url: "/online-resources"
  - name: "Grants & Projects"
    weight: 3
    url: "/grants-and-projects"
  - name: "Training & Event Materials"
    weight: 4
    url: "/training-materials"
  - name: "FAQ"
    weight: 5
    url: "/faq"

the_standard:
  - name: "Specification"
    weight: 1
    url: "https://nwb-schema.readthedocs.io/en/latest/format.html"
  - name: "Policies"
    weight: 2
    url: "/policies"
  - name: "Enhancement Proposals"
    weight: 3
    url: "/enhancement-proposals"
  - name: "Extensions (NDX Catalog)"
    weight: 4
    url: "https://nwb-extensions.github.io"
